import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../../context/AppContext';
import { theme } from '../../theme/theme';

export const CaregiverAlertsScreen: React.FC = () => {
  const { alerts, acknowledgeAlert, clearAcknowledgedAlerts, triggerSos } = useApp();
  const [filter, setFilter] = useState<'all' | 'active' | 'critical' | 'resolved'>('all');

  const activeAlerts = alerts.filter(a => !a.acknowledged);
  const criticalAlerts = alerts.filter(a => a.severity === 'critical');
  const resolvedAlerts = alerts.filter(a => a.acknowledged);

  const filteredAlerts = alerts.filter(a => {
    if (filter === 'all') return true;
    if (filter === 'active') return !a.acknowledged;
    if (filter === 'critical') return a.severity === 'critical';
    if (filter === 'resolved') return a.acknowledged;
    return true;
  });

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.headerRow}>
        <View>
          <Text style={styles.title}>Alerts & Notifications</Text>
          <Text style={styles.sub}>Safety alerts, missed doses & SOS dispatches</Text>
        </View>

        <TouchableOpacity
          style={styles.simulateBtn}
          onPress={() => triggerSos('Demo test emergency alert generated by caregiver.')}
        >
          <Ionicons name="flash" size={16} color="#FFFFFF" />
          <Text style={styles.simulateBtnText}>Simulate SOS</Text>
        </TouchableOpacity>
      </View>

      {/* Filter Chips Bar */}
      <View style={styles.filterRow}>
        <TouchableOpacity
          style={[styles.filterChip, filter === 'all' && styles.filterChipActive]}
          onPress={() => setFilter('all')}
        >
          <Text style={[styles.filterChipText, filter === 'all' && styles.filterChipTextActive]}>
            ALL ({alerts.length})
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.filterChip, filter === 'active' && styles.filterChipActive]}
          onPress={() => setFilter('active')}
        >
          <Text style={[styles.filterChipText, filter === 'active' && styles.filterChipTextActive]}>
            ACTIVE ({activeAlerts.length})
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.filterChip, filter === 'critical' && styles.filterChipActive]}
          onPress={() => setFilter('critical')}
        >
          <Text style={[styles.filterChipText, filter === 'critical' && styles.filterChipTextActive]}>
            SOS ({criticalAlerts.length})
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.filterChip, filter === 'resolved' && styles.filterChipActive]}
          onPress={() => setFilter('resolved')}
        >
          <Text style={[styles.filterChipText, filter === 'resolved' && styles.filterChipTextActive]}>
            RESOLVED ({resolvedAlerts.length})
          </Text>
        </TouchableOpacity>
      </View>

      {/* Clear Acknowledged Option */}
      {resolvedAlerts.length > 0 && filter !== 'active' && (
        <TouchableOpacity style={styles.clearBtn} onPress={clearAcknowledgedAlerts}>
          <Ionicons name="trash-bin-outline" size={16} color="#64748B" />
          <Text style={styles.clearBtnText}>Clear {resolvedAlerts.length} Resolved Alerts</Text>
        </TouchableOpacity>
      )}

      {filteredAlerts.length === 0 ? (
        <View style={styles.emptyCard}>
          <Ionicons name="checkmark-done-circle" size={48} color="#10B981" />
          <Text style={styles.emptyTitle}>No {filter !== 'all' ? filter : ''} alerts</Text>
          <Text style={styles.emptySub}>All safety alerts are accounted for.</Text>
        </View>
      ) : (
        filteredAlerts.map(alert => (
          <View
            key={alert.id}
            style={[
              styles.alertCard,
              alert.severity === 'critical' && styles.cardCritical,
              alert.acknowledged && styles.cardAcknowledged,
            ]}
          >
            <View style={styles.alertHeaderRow}>
              <Ionicons
                name={
                  alert.type === 'sos'
                    ? 'alarm'
                    : alert.type === 'missed_medicine'
                    ? 'time'
                    : 'heart'
                }
                size={24}
                color={
                  alert.acknowledged
                    ? '#64748B'
                    : alert.severity === 'critical'
                    ? '#DC2626'
                    : '#D97706'
                }
              />
              <Text style={[styles.alertTitle, alert.acknowledged && styles.textMuted]}>
                {alert.title}
              </Text>
              <View
                style={[
                  styles.severityChip,
                  {
                    backgroundColor: alert.acknowledged
                      ? '#E2E8F0'
                      : alert.severity === 'critical'
                      ? '#FEE2E2'
                      : '#FEF3C7',
                  },
                ]}
              >
                <Text
                  style={[
                    styles.severityText,
                    {
                      color: alert.acknowledged
                        ? '#64748B'
                        : alert.severity === 'critical'
                        ? '#991B1B'
                        : '#92400E',
                    },
                  ]}
                >
                  {alert.acknowledged ? 'RESOLVED' : alert.severity.toUpperCase()}
                </Text>
              </View>
            </View>

            <Text style={[styles.alertMessage, alert.acknowledged && styles.textMuted]}>
              {alert.message}
            </Text>

            <View style={styles.alertFooter}>
              <Text style={styles.timestampText}>
                Logged at{' '}
                {new Date(alert.timestamp).toLocaleTimeString([], {
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </Text>
              {!alert.acknowledged ? (
                <TouchableOpacity
                  style={styles.ackBtn}
                  onPress={() => acknowledgeAlert(alert.id)}
                >
                  <Text style={styles.ackBtnText}>Mark Acknowledged</Text>
                </TouchableOpacity>
              ) : (
                <Text style={styles.ackLabel}>✓ Acknowledged</Text>
              )}
            </View>
          </View>
        ))
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  sub: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 2,
  },
  simulateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#DC2626',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  simulateBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
  },
  filterChipActive: {
    backgroundColor: '#2563EB',
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#475569',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
  },
  clearBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  clearBtnText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E293B',
    marginTop: 12,
  },
  emptySub: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 4,
  },
  alertCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: theme.borderRadius.medium,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#F59E0B',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  cardCritical: {
    borderLeftColor: '#DC2626',
    backgroundColor: '#FEF2F2',
  },
  cardAcknowledged: {
    borderLeftColor: '#94A3B8',
    backgroundColor: '#FAFAFA',
  },
  alertHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0F172A',
    marginLeft: 10,
    flex: 1,
  },
  textMuted: {
    color: '#64748B',
  },
  severityChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  severityText: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  alertMessage: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 20,
    marginTop: 2,
  },
  alertFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  timestampText: {
    fontSize: 12,
    color: '#94A3B8',
  },
  ackBtn: {
    backgroundColor: '#2563EB',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  ackBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12,
  },
  ackLabel: {
    color: '#10B981',
    fontWeight: 'bold',
    fontSize: 13,
  },
});
